### ISSUE TITLE
Indexer BindException

### ISSUE THREAD

**Issue by capdeploy** [archivesspace/archivesspace#130]
Hi there,

I'm trying to install version 1.1.2 clean and when starting it up the indexer complains that the port is already in use, the version we had been running (1.0.9) doesn't have this problem.  The error is:
2015-02-09 19:17:37.360:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:8091: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:182)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:260)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.Server.doStart(Server.java:283)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:440)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:304)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:52)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
	at launcher.launcher.method__1$RUBY$start_server(launcher/launcher.rb:86)
	at launcher$launcher$method__1$RUBY$start_server.call(launcher$launcher$method__1$RUBY$start_server)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
	at org.jruby.internal.runtime.methods.CompiledMethod.call(CompiledMethod.java:268)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at launcher.launcher.chained_4_rescue_1$RUBY$SYNTHETICmain(launcher/launcher.rb:152)
	at launcher.launcher.method__3$RUBY$main(launcher/launcher.rb:145)
	at launcher$launcher$method__3$RUBY$main.call(launcher$launcher$method__3$RUBY$main)
	at launcher$launcher$method__3$RUBY$main.call(launcher$launcher$method__3$RUBY$main)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
	at launcher.launcher.__file__(launcher/launcher.rb:230)
	at launcher.launcher.load(launcher/launcher.rb)
	at org.jruby.Ruby.runScript(Ruby.java:811)
	at org.jruby.Ruby.runScript(Ruby.java:804)
	at org.jruby.Ruby.runNormally(Ruby.java:673)
	at org.jruby.Ruby.runFromMain(Ruby.java:522)
	at org.jruby.Main.doRunFromMain(Main.java:395)
	at org.jruby.Main.internalRun(Main.java:290)
	at org.jruby.Main.run(Main.java:217)
	at org.jruby.Main.main(Main.java:197)
2015-02-09 19:17:37.365:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@5c3de68d: java.net.BindException: Address already in use
java.net.BindException: Address already in use

Please help!

**Comment by cfitz** [comment]
Hi, 

Are you running on a PC? Is anything running on port 8091? You can also change the indexer port from 8091 to something else ( like 8088 )

**Comment by capdeploy** [comment]
Hi there, its a linux ec2 instance, and nothing it on that port, only when the app (trys) to start, then that port frees up when it stops, its almost as if the app is trying to start it 2x

**Comment by cfitz** [comment]
Hi. Is this still an issue?
