### ISSUE TITLE
Export to PDF Fails for Every Resource

### ISSUE THREAD

**Issue by maxlharr** [archivesspace/archivesspace#2085]
I am running ArchivesSpace 2.8.1 on a Windows install against a local MySQL database. 

I'm running into a problem where, when I try to export any of my resources finding aids as a PDF, the background job fails. This is happening for every resource in my repository. Each time, the log gives me this output:

`Generating`` PDF for Charles Stuart Store records  
undefined method `make_tmpname' for Dir::Tmpname:Module
uri:classloader:/asutils.rb:76:in `tempfile_name'
C:/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/AS_fop_external.rb:17:in `initialize'
C:/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/job_runners/print_to_pdf_runner.rb:49:in `block in run'
C:/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/request_context.rb:24:in `open'
C:/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/job_runners/print_to_pdf_runner.rb:14:in `run'
C:/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/background_job_queue.rb:126:in `run_pending_job'
C:/archivesspace/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/lib/background_job_queue.rb:169:in `block in `start_background_thread'`

I've seen some similar issues with PDF exports failing, but none seem to match this sort of output in the log. Is there something obvious I'm missing?

**Comment by fordmadox** [comment]
That's not good!

I haven't tested anything out yet, but based on the helpful output that you attached, I'm guessing this is due to the "make_tmpname" method being deprecated (see https://github.com/archivesspace/archivesspace/blob/1c22d0375d3508d30cb4e51e86506a2d5cf50da7/common/asutils.rb#L76, but ASpace was just updated to use ruby 2.5, which no longer has that method).  

In case it helps someone else add a patch, this S.O. page has more info, with a variety of fixes mentioned:  https://stackoverflow.com/questions/13787746/creating-a-thread-safe-temporary-file-name
