### ISSUE TITLE
PUI Print to PDF fails if & Followed by a number

### ISSUE THREAD

**Issue by seanlw** [archivesspace/archivesspace#2324]
We have an archival object with the title `2217, Hines, Galleria North 1&2, 2000-04-10` and failed to create and PDF at the resource level.

This has been confirmed on our testing of ArchivesSpace version 3.0.1

## Expected Behavior
1. Go to the resource page
2. click PDF
3. PDF is downloaded by user

## Current Behavior
After clicking the PDF button for awhile, an error page displays

logs:
```
F, [2021-06-29T13:32:39.732702 #5980] FATAL -- : [678f93d5-8a58-4aee-b70f-377ab5a8ffa4]
F, [2021-06-29T13:32:39.733275 #5980] FATAL -- : [678f93d5-8a58-4aee-b70f-377ab5a8ffa4] RuntimeError (Failed to clean XML: The entity name must immediately follow the '&' in the entity reference.):
F, [2021-06-29T13:32:39.733485 #5980] FATAL -- : [678f93d5-8a58-4aee-b70f-377ab5a8ffa4]
F, [2021-06-29T13:32:39.733702 #5980] FATAL -- : [678f93d5-8a58-4aee-b70f-377ab5a8ffa4] app/lib/xml_cleaner.rb:32:in `clean'
[678f93d5-8a58-4aee-b70f-377ab5a8ffa4] app/models/finding_aid_pdf.rb:94:in `generate'
[678f93d5-8a58-4aee-b70f-377ab5a8ffa4] app/controllers/pdf_controller.rb:15:in `resource'
```

## Possible Solution
Putting a space after `&` does result in the PDF being generated and downloaded, however, changing the title is not the desired fix.

Line 43 in `public/app/lib/xml_cleaner.rb` might need to look for numbers as well as letters

`if line.match(/&\s+/) || line.match(/&[A-Za-z]+[^;]/)` --> `if line.match(/&\s+/) || line.match(/&[A-Za-z1-9]+[^;]/)`

## Steps to Reproduce (for bugs)
1. Go to resource http://fatest.lib.uh.edu/repositories/2/resources/214 (testing environment behind firewall)
2. Click PDF button

## Context

User unable to view PDF of resource

## Your Environment

ArchivesSpace 3.0.1 on Ubuntu 18.04

**Comment by fordmadox** [comment]
Just a note that it looks like this issue has been patched (twice), so the issue can be closed, right?
