### ISSUE TITLE
3.0.2 release zip - Public Interface cannot find sassc-2.4.0

### ISSUE THREAD

**Issue by Hurlyburly2** [archivesspace/archivesspace#2357]
The public interface does not seem to startup properly with the zipped 3.0.2 release. Upon startup, the error is:
```
org.jruby.rack.RackInitializationException: Could not find sassc-2.4.0 in any of the sources
```
We have seen this behavior on two machines so far. To duplicate, download and unzip the 3.0.2 release. Then run ./archivesspace.sh.

## Expected Behavior
Public interface should startup properly

## Current Behavior
The error above appears when the public interface is starting up. Then, upon visiting localhost:8081, the following error is displayed:
```
Could not find sassc-2.4.0 in any of the sources from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize' from org/jruby/RubyArray.java:2609:in `map!' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in requested_specs' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <main>' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence' from /Users/dougsimon/projects/archivesspace302/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<main>' from org/jruby/RubyKernel.java:974:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:130:in `require' from /Users/dougsimon/projects/archivesspace302/data/tmp/jetty-0.0.0.0-8081-public.war-_-any-/webapp/WEB-INF/config/boot.rb:10:in `<main>' from org/jruby/RubyKernel.java:974:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require' from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `load_environment' from uri:classloader:/jruby/rack/rails_booter.rb:83:in `load_environment' from <script>:1:in `<main>' from launcher/launcher.rb:89:in `start_server' from launcher/launcher.rb:167:in `main' from launcher/launcher.rb:258:in `<main>'
```

## Possible Solution
There doesn't appear to be a difference between 3.0.2-RC and 3.0.2 that would cause this, which may indicate an unintended gem update? 

## Steps to Reproduce (for bugs)
See above

## Context
We are working to update our ArchivesSpace to version 3.0.2, and have been working with the release candidate. We noticed this problem after we switched to the new 3.0.2 release. This issue does not appear in the release candidate.

**Comment by quoideneuf** [comment]
@Hurlyburly2 Thank you - this is a known issue which I neglected to avoid when building this release. It has been rebuilt and should be fine now (you will need to re-download). Please reopen if that is not the case.
