### ISSUE TITLE
Viewing search result yields a Error 500

### ISSUE THREAD

**Issue by rcarsey1** [archivesspace/archivesspace#2521]
In the staff interface, we do a search which returns 3 Person and 1 Corporate Entity records.    The first two seem to be duplicates of each other (same "Title" for both, and all of the "found in", "identifier" and "dates" are all blank).  The duplicates have two different ID#'s.. so they are indeed two different objects. 

Clicking on the View link of one of htem takes us to:  [https://archives-management.monmouth.edu/agents/agent_person/9351](url), which yields an error message.

The log file states:

```
F, [2021-11-10T15:19:48.213340 #10678] FATAL -- :
F, [2021-11-10T15:19:48.213438 #10678] FATAL -- : app/controllers/agents_controller.rb:34:in 'show'
app/controllers/application_controller.rb:797:in 'set_locale'
I, [2021-11-10T15:19:49.907195 #10678]  INFO -- : Started GET "/agents/agent_person/9351" for 2620:3a:c000:42::2:f62a at 2021-11-10 15:19:49 -0500
I, [2021-11-10T15:19:49.909193 #10678]  INFO -- : Processing by AgentsController#show as HTML
I, [2021-11-10T15:19:49.909365 #10678]  INFO -- :   Parameters: {"agent_type"=>"agent_person", "id"=>"9351"}
I, [2021-11-10T15:19:50.152760 #10678]  INFO -- : Completed 500 Internal Server Error in 243ms
F, [2021-11-10T15:19:50.154259 #10678] FATAL -- :
F, [2021-11-10T15:19:50.154479 #10678] FATAL -- : RuntimeError ({"error":{"structured_date_range":["Must specify range date for date type of range"]},"warning":{},"invalid_object":"#<JSONModel(:structured_date_label) {\"create_time\"=>\"2021-06-17T17:01:02Z\", \"system_mtime\"=>\"2021-06-17T17:01:02Z\", \"user_mtime\"=>\"2021-06-17T17:01:02Z\", \"lock_version\"=>0, \"date_type_structured\"=>\"range\", \"date_label\"=>\"agent_relation\", \"date_era\"=>\"ce\", \"date_calendar\"=>\"gregorian\", \"jsonmodel_type\"=>\"structured_date_label\", \"structured_date_single\"=>{\"date_standardized\"=>\"1960\", \"create_time\"=>\"2021-06-17T17:01:02Z\", \"system_mtime\"=>\"2021-06-17T17:01:02Z\", \"user_mtime\"=>\"2021-06-17T17:01:02Z\", \"lock_version\"=>0, \"date_role\"=>\"end\", \"date_standardized_type\"=>\"standard\", \"jsonmodel_type\"=>\"structured_date_single\"}}>"}
):
F, [2021-11-10T15:19:50.154549 #10678] FATAL -- :
```
## My Environment

* Version used:  3.1.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 95.0.4638.69
* Operating System and version (desktop or mobile): Win 10

**Comment by cdibella** [comment]
Closing here since it was submitted separately as a technical support ticket.
