### ISSUE TITLE
AS 1.4.1, JRuby 1.7.22, require_relative in jar issues

### ISSUE THREAD

**Issue by shorock** [archivesspace/archivesspace#315]
Sysadmin here.  Upgrading/upgraded to 1.4.1. Our setup: Linux, deploy to Tomcat 7/Java 8, external Solr.

Started seeing this.
```
Oct 15, 2015 11:52:14 AM org.apache.catalina.core.ApplicationContext log
SEVERE: ERROR: initialization failed
org.jruby.rack.RackInitializationException: **No such file or directory - /home/ec2-user/apache-tomcat-7.0.64/file:/home/ec2-user/apache-tomcat-7.0.64/lib/common.jar!/jsonmodel.rb**
        from org/jruby/RubyFile.java:840:in `realpath'
        from file:/home/ec2-user/apache-tomcat-7.0.64/lib/jruby-core-1.7.22.jar!/jruby/kernel19/kernel.rb:11:in `require_relative'
        from file:/home/ec2-user/apache-tomcat-7.0.64/lib/common.jar!/jsonmodel.rb:4:in `(root)'
        from org/jruby/RubyKernel.java:1040:in `require'
        from /home/ec2-user/apache-tomcat-7.0.64/lib/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'

 .... can provide more trace if needed  

Caused by: org.jruby.exceptions.RaiseException: (Errno::ENOENT) /home/ec2-user/apache-tomcat-7.0.64/file:/home/ec2-user/apache-tomcat-7.0.64/lib/common.jar!/jsonmodel.rb
        at org.jruby.RubyFile.realpath(org/jruby/RubyFile.java:840)
        at RUBY.require_relative(file:/home/ec2-user/apache-tomcat-7.0.64/lib/jruby-core-1.7.22.jar!/jruby/kernel19/kernel.rb:11)
        at RUBY.(root)(file:/home/ec2-user/apache-tomcat-7.0.64/lib/common.jar!/jsonmodel.rb:4)
```

Which didn't happen to me when testing.  Hmm.  Figured out that I was getting both the jruby-jars 1.7.21 jars (from public/Gemfile) and 1.7.22 (from the other Gemfiles).  If I use the 1.7.21 jars alone, no problem.  Use the 1.7.22 ones alone, the above problem appears (and appears if I only use 1.7.22 in a Jetty install).

Looks like JRuby 1.7.22 changed require_relative() behavior a bit:
https://github.com/jruby/jruby/issues/3169
https://github.com/jruby/jruby/issues/3176

and I'm seeing some discussion of this in other Rails/JRuby projects that put a bunch of gems in a jar (i.e., common.jar)

Since public/Gemfile still required JRuby 1.7.21, the problem is hiding for most people unless your classpath decides to get the 1.7.22 ones first (which my Tomcat does... sometimes).

Unless we're depending on anything 1.7.22, the current workaround for someone seeing that ENOENT error is to remove the 1.7.22 jars.

**Comment by cfitz** [comment]
Hi,

Try this one:
https://github.com/archivesspace/archivesspace/releases/tag/v1.4.3-rc1

Let us know if that works. I synch'ed the jruby versions. Also, if you're using TC, be sure to remove any older libraries from your classpath.

**Comment by shorock** [comment]
It didn't.  For testing, I installed from the ZIP in a clean test VM (& copy of existing DB), no mucking with Tomcat or an external Solr.

Did see only 1.7.22 JRuby.

```
2015-10-21 16:20:04.134:WARN:/:ERROR: initialization failed
...
Caused by:
org.jruby.exceptions.RaiseException: (ENOENT) No such file or directory - /home/ec2-user/archivesspace/file:/home/ec2-user/archivesspace/lib/common.jar!/jsonmodel.rb
        at org.jruby.RubyFile.realpath(org/jruby/RubyFile.java:840)
        at RUBY.require_relative(file:/home/ec2-user/archivesspace/gems/gems/jruby-jars-1.7.22/lib/jruby-core-1.7.22.jar!/jruby/kernel19/kernel.rb:11)
        at RUBY.(root)(file:/home/ec2-user/archivesspace/lib/common.jar!/jsonmodel.rb:4)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
at ActiveSupport::Dependencies::Loadable.require(/home/ec2-user/archivesspace/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251)
        at ActiveSupport::Dependencies::Loadable.load_dependency(/home/ec2-user/archivesspace/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236)
        at ActiveSupport::Dependencies::Loadable.require(/home/ec2-user/archivesspace/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251)
        at RUBY.(root)(/home/ec2-user/archivesspace/data/tmp/jetty-0.0.0.0-8081-public.war-_-any-/webapp/WEB-INF/config/initializers/json_object.rb:1)
```

Again, having trouble with require()-ing (calling require_relative()) of things in common.jar with the changes to require_relative in JRuby 1.7.22.

I do get things working if I expand common/ back to the archivesspace root (like building dev), add it to the startup classpath, and remove the common.jar.

**Comment by cfitz** [comment]
hm, whats weird is these require_relative issues are marked as resolved for 1.7.22. 

Can you try:
https://github.com/archivesspace/archivesspace/releases/tag/v1.4.2-rc2

This has jruby 1.7.21, which should have the same require_relative as 1.7.18 ( which is what 1.3.0 used )

Does that work?

**Comment by shorock** [comment]
Reverting to 1.7.21 works fine.  Not, fwiw, a Windows problem on my end (Linux x64, testing on AWS).

I think this jruby issue is closer to what I'm seeing. https://github.com/jruby/jruby/issues/3401

It looks like jruby people may still be working through these things in just the last 2-3 days (linked issue https://github.com/jruby/jruby/issues/3270 from the above).  Or we may need to do like #3401 above did and just use non-relative-requires in the common.jar ruby files.

**Comment by cfitz** [comment]
Thanks. We'll have to keep an eye on this since this issue is in jruby 9000 as well...

Fixed in v.1.4.2
