### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by brandles** [archivesspace/archivesspace#616]
Running mac os sierra, latest java, and upon running the .sh file, I (and four other people on similar machines) get an error ending in this:

	at launcher.launcher.__file__(launcher/launcher.rb:238)
	at launcher.launcher.load(launcher/launcher.rb)
	at org.jruby.Ruby.runScript(Ruby.java:867)
	at org.jruby.Ruby.runScript(Ruby.java:860)
	at org.jruby.Ruby.runNormally(Ruby.java:729)
	at org.jruby.Ruby.runFromMain(Ruby.java:578)
	at org.jruby.Main.doRunFromMain(Main.java:395)
	at org.jruby.Main.internalRun(Main.java:290)
	at org.jruby.Main.run(Main.java:217)
	at org.jruby.Main.main(Main.java:197)
Error: Some library (perhaps JRuby) was built with a later JVM version.

**Comment by cfitz** [comment]
I have mac os 10.12.3 and java version "1.8.0_25". 
Which version are you trying to run?

**Comment by brandles** [comment]
I tried the top 2 versions on the list in github on 2 separate machines,
same exact errors.

**Comment by brandles** [comment]
if you meant java,
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
Mac 10.12.1

**Comment by cfitz** [comment]
That was going to be my next question. 
You need to upgrade to either java 7 or 8. The documentation still says it supports 6,  but that is obviously incorrect. The updated version of Solr requires at least 7.

**Comment by lmcglohon** [comment]
Closed with PR #617
