### ISSUE TITLE
EAD import broken in march-release

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#658]
```
     [java] D, [2017-03-16T21:44:28.179910 #7819] DEBUG -- : Thread-2146: Running job 8 on background job thread 1 (2008)
     [java] E, [2017-03-16T21:44:28.224859 #7819] ERROR -- : 
     [java] wrong number of arguments (1 for 0)
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/converters/lib/xml_sax.rb:154:in `handle_opener'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/converters/lib/xml_sax.rb:106:in `block in run'
     [java] /projects/Archivespace/dcs-archivesspace/build/gems/gems/nokogiri-1.7.0.1-java/lib/nokogiri/xml/reader.rb:107:in `each'
     [java] org/jruby/RubyEnumerable.java:1067:in `each_with_index'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/converters/lib/xml_sax.rb:88:in `run'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/lib/job_runners/batch_import_runner.rb:69:in `block in run'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/lib/request_context.rb:24:in `open'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/lib/job_runners/batch_import_runner.rb:65:in `block in run'
     [java] org/jruby/RubyArray.java:1734:in `each'
     [java] org/jruby/RubyEnumerable.java:1067:in `each_with_index'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/lib/job_runners/batch_import_runner.rb:61:in `block in run'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/model/db.rb:119:in `block in open'
     [java] org/jruby/RubyFixnum.java:305:in `times'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/model/db.rb:107:in `open'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/model/db.rb:432:in `block in DB'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/lib/job_runners/batch_import_runner.rb:57:in `run'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/lib/background_job_queue.rb:126:in `run_pending_job'
     [java] /projects/Archivespace/dcs-archivesspace/backend/app/lib/background_job_queue.rb:169:in `block in start_background_thread'
```

I added some tracing to the code and it appears to break on [ignore "titlepage" in ead_converter.rb](https://github.com/archivesspace/archivesspace/blob/march-release/backend/app/converters/ead_converter.rb#L98)

The following change to xml_sax.rb appears to fix it for me:

```
--- a/backend/app/converters/lib/xml_sax.rb
+++ b/backend/app/converters/lib/xml_sax.rb
@@ -31,8 +31,8 @@ module ASpaceImport
         end
 
         def ignore(path)
-          with(path) { @ignore = true }
-          and_in_closing(path) { @ignore = false }
+          with(path) { |*| @ignore = true }
+          and_in_closing(path) { |*| @ignore = false }
         end
```

Although I'm not sure I completely understand why: just mimicking the calling convention changes in the rest of the ead_converter code. No idea what arguments are being ignored & guessing this must be for compatibility with newer nokogiri.

**Comment by marktriggs** [comment]
Urk, thanks Steve!  I've applied your fix and updated the test suite to catch this case.

The difference in calling convention comes about because of the Ruby upgrade.  In Ruby 1.9, blocks didn't check their argument counts, so you could call a proc expecting zero arguments with however many you wanted and it wouldn't care.  The XML SAX code here was making use of that all over the place--these blocks have always been receiving one extra (ignored) argument, but it didn't matter until we moved to Ruby 2.x.  I couldn't see any other places I'd missed, so hopefully that's all of them.
