### ISSUE TITLE
PUI: Error when sending confirmation email in Request feature

### ISSUE THREAD

**Issue by cvonkleist** [archivesspace/archivesspace#964]
In ArchivesSpace 2.1.2, we're getting the following error when a PUI user tries to use the Request feature:

```
INFO: F, [2017-09-11T06:26:00.108028 #24961] FATAL -- :
[...] ActionView::Template::Error (undefined method `app_prefix' for #<#<Class:0x713ba38>:0x2026b629>):

INFO: F, [2017-09-11T06:26:00.117393 #24961] FATAL -- :
[...]     4:   <h2>Record Requested</h2>
[...]     5:   <strong>Title</strong>: <%= @request.title %><br>
[...]     6:   <% url = "#{AppConfig[:public_proxy_url].sub(/\/^/, '')}#{@request.request_uri}" %>
[...]     7:   <strong>URL</strong>: <%= link_to url, app_prefix(url) %>
[...]     8: </div>
[...]     9:
[...]    10: <div class="user">

INFO: F, [2017-09-11T06:26:00.131270 #24961] FATAL -- :
[...]

INFO: F, [2017-09-11T06:26:00.138020 #24961] FATAL -- :
[...] app/views/request_mailer/request_received_email.html.erb:7:in `_app_views_request_mailer_request_received_email_html_erb__232391451_2272'
[...] app/mailers/request_mailer.rb:7:in `request_received_email'
[...] app/controllers/requests_controller.rb:11:in `make_request'
```

It seems that the `app_prefix()` helper method is not available in the scope of the `request_received_email.html.erb` view. I believe this is the relevant code:

https://github.com/archivesspace/archivesspace/blob/4cd7f12701cacb7da30a62886131922dc05123db/public/app/views/request_mailer/request_received_email.html.erb#L1-L19

**Comment by lmcglohon** [comment]
@cvonkleist The issue is that app_prefix is not needed here since the url already has the public_proxy_url. I have the fix and will create a pull request with the fix.
